services:
  ml:
    build:
      context: ./ml
      cache_from:
        - ml-cache
    ports:
      - "8000:8000"

  backend:
    build:
      context: ./backend
    ports:
      - "5000:5000"

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"